spring.application.name=ybase-spring-boot-ai-gemini-llm
#h2 database configuration
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true


# Google Gemini API Configurations
spring.ai.google.genai.api-key=AIzaSyDYd4E8COdykEQCdbDLumk9sMCgKsW3WuY
spring.ai.google.genai.chat.model=gemini-2.5-flash


 
# H2 Database
#spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.driver-class-name=org.h2.Driver

# Ollama Configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2

# MCP Server Configuration
spring.ai.mcp.server.name=student-database-mcp-server
spring.ai.mcp.server.version=1.0.0